### ISSUE TITLE
tricontour.jl is capitalized, which stops package from installing on linux 

### ISSUE THREAD

**Issue by perrinmeyer** [pazner/Triplot.jl#1] opened 2021-01-26 04:28 UTC
The function Tricontour.jl is capitalized in /src, .  When I renamed it tricontour.jl, I was able to install the package in linux / julia 1.5.3

Very useful package, thanks!!!! 

julia> using Triplot
[ Info: Precompiling Triplot [a1624b44-3529-439a-b7d2-9284cf832a73]
ERROR: LoadError: could not open file /home/perrinmeyer/.julia/packages/Triplot/Y2uMz/src/tricontour.jl
Stacktrace:
 [1] include(::Function, ::Module, ::String) at ./Base.jl:380
 [2] include at ./Base.jl:368 [inlined]
 [3] include(::String) at /home/perrinmeyer/.julia/packages/Triplot/Y2uMz/src/Triplot.jl:1
 [4] top-level scope at /home/perrinmeyer/.julia/packages/Triplot/Y2uMz/src/Triplot.jl:8
 [5] include(::Function, ::Module, ::String) at ./Base.jl:380
 [6] include(::Module, ::String) at ./Base.jl:368
 [7] top-level scope at none:2
 [8] eval at ./boot.jl:331 [inlined]
 [9] eval(::Expr) at ./client.jl:467
 [10] top-level scope at ./none:3
in expression starting at /home/perrinmeyer/.julia/packages/Triplot/Y2uMz/src/Triplot.jl:8
ERROR: Failed to precompile Triplot [a1624b44-3529-439a-b7d2-9284cf832a73] to /home/perrinmeyer/.julia/compiled/v1.5/Triplot/9U8ze_nCOAr.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1305
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923

**Comment by pazner** [comment] 2021-01-26 05:46
Thanks for pointing this out. It was caused by the case insensitive filesystem on the Mac.

I pushed a fixed. Does it work for you now?

**Comment by perrinmeyer** [comment] 2021-01-26 06:21
yes, it works now.  I'm new to GR (I've mainly used PyPlot.jl and dabbled a bit in Makie.jl  Mackie seems really "modern" and powerful, but insanely slow and rather complicated... GR seems like a good balance -- seems to load MUCH quicker than Makie.jl. ).  

quick question -- how do I change the PNG resolution?   

thanks again

**Comment by pazner** [comment] 2021-01-26 06:55
Great, glad it's working for you!

You can change the PNG resolution with `GR.setwsviewport`, but the arguments are in meters rather than pixels (for some reason… see also jheinen/GR.jl#50), so you might have to experiment to find the appropriate values.

**Comment by pazner** [comment] 2021-01-26 18:09
Closing since this seems to be resolved… feel free to reopen if needed.

**Closed as completed by pazner** 2021-01-26 18:09 UTC
